version: "3"

services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=quan0401
      - MONGO_PWD=mypassword
    command: npm run dev
