version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build:
      context: .
      platforms:
        - linux/amd64 # Adjust to the desired platform
    image: quan0401/node-app
    # ports:
    #   - "3000-3001:3000"
    # No need to publish ports for our node-application since now we use nginx
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    # depends on mongo so mongo service will be started first
    depends_on:
      - mongo
      - redis
    # env_file:
    #   - ./.env

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
