version: "3"

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    # depends on mongo so mongo service will be started first
    depends_on:
      - mongo
    # env_file:
    #   - ./.env
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
